### ISSUE TITLE
[QUESTION] - Use local assets files (gltf)

### ISSUE THREAD

**Issue by Ahmadre** [drydart/model_viewer.dart#1]
I want use my own asset in my asset folder of flutter, but in the example code I only see an "URL" parameter. Can I use local assets?

Thanks for this package :)

Best regards.

**Comment by Ahmadre** [comment]
nevermind. I had the best results with the unity plugin

**Comment by artob** [comment]
I added an FAQ entry for your question: https://github.com/drydart/model_viewer.dart#q-how-do-i-load-a-local-asset-instead-of-loading-a-url

**Comment by artob** [comment]
As of the [0.8.0](https://pub.dev/packages/model_viewer) release, loading bundled assets is now supported.
