### ISSUE TITLE
Object not loading in AR

### ISSUE THREAD

**Issue by ykrishna5** [drydart/model_viewer.dart#4]
When clicked on AR button 3d object is not loading in AR(in the real world). 

[Screenshot](https://drive.google.com/file/d/1_IfUEzmfNx4HNENEawDXsZSVjZ37EkBL/view?usp=sharing)

**Comment by artob** [comment]
Thanks for the bug report, I will attempt to reproduce and endeavor to figure out what's causing that.

**Comment by iamrmrishan** [comment]
Same issue happening to me also.

**Comment by artob** [comment]
I've reproduced the problem and confirmed that it's a known issue upstream: https://github.com/google/model-viewer/issues/743

I will attempt to work around the limitation in a future release as described in the aforementioned issue.

**Comment by artob** [comment]
@ykrishna5 @iamrmrishan This issue has been fixed in the [0.7.0 release](https://pub.dev/packages/model_viewer). Please upgrade and give it another try.
